# Generated by Django 3.1.1 on 2020-09-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Password_Generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Organization',
            field=models.TextField(max_length=300),
        ),
    ]
