# Generated by Django 3.1.7 on 2021-02-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Password_Generator', '0002_auto_20200930_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Organization',
            field=models.CharField(max_length=300),
        ),
    ]
